version: '3.1'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: emilia
      POSTGRES_PASSWORD: landgrebe
    ports:
      - 5433:5432
